### ISSUE TITLE
Billboard [Erro de implementação]

### ISSUE THREAD

**Issue by pulgamecanica** [ULHT-PW-2020-21/pw-python-01#1]
No Exemplo do Billboard penso que ha um erro no Exemplo dado.
O exemplo diz:

> Introduza uma sequencia de carateres: abcdefghi
Introduza um inteiro: -2
Resultado de deslocação de 3 carateres: defghiabc

Mais se é deslocado duas pocisoes para a esquerda devia ser: "**cdefghiab**"
Tambem, na última frase, diz:

> Resultado de deslocação de 3 carateres: defghiabc

E em nenhum momento se indicou deslocação de 3 carateres, o número inserido foi -2....

**Comment by luciostuder** [comment]
correto, devia ser -3

**Comment by pulgamecanica** [comment]
Boa! 👍 
Bom fim de semana. :)
